# Generated by Django 5.0.1 on 2024-02-09 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reptile',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(max_length=50)),
                ('notes', models.TextField()),
                ('reptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptiles.reptile')),
            ],
        ),
    ]
